name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/Enrole
            git pull origin main

      - name: Purge jsDelivr cache
        run: |
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/style.css"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/style2.css"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/scripts/footer.js"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/scripts/topbar.js"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/scripts/sidebar-menu.js"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/scripts/category-loader.js"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/scripts/utils.js"
          curl -s "https://purge.jsdelivr.net/gh/Bergen-Community-College/Enrole@main/style.js"
